# The name of your plugin as displayed in the Plugins Catalog web UI.
displayName: honeypot-middleware

# For now, `middleware` is the only type available.
type: middleware

# The import path of your plugin.
import: github.com/CorySanin/honeypot-middleware

# A brief description of what your plugin is doing.
summary: Serve fake files to vulnerability crawlers

# Medias associated to the plugin (optional)
iconPath: .assets/icon.png
# bannerPath: foo/banner.png

# Configuration data for your plugin.
# This is mandatory,
# and Plugins Catalog will try to execute the plugin with the data you provide as part of its startup validity tests.
testData:
  verbose: false
  phpInfoPatterns:
    - /phpinfo[0-9]?\.php$
  executionPatterns:
    - /xmlrpc\.php$
  dotEnvPatterns:
    - \.env$
  wlwmanifestPatterns:
    - /wlwmanifest\.xml$
