services:
  traefik:
    image: traefik:v3.6
    restart: 'no'
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/config
      - ./:/plugins-local/src/github.com/CorySanin/honeypot-middleware
    command:
      - --configFile=/config/traefik.yml
  
  target:
    image: traefik/whoami:latest
    labels:
      - traefik.enable=true
      - traefik.http.routers.target.rule=Host(`localhost`)
      - traefik.http.routers.target.entrypoints=web
      - traefik.http.routers.target.service=target
      - traefik.http.routers.target.middlewares=honeypot@file
      - traefik.http.services.target.loadbalancer.server.port=80
