entrypoints:
  web:
    address: ':80'
providers:
  docker: true
  file:
    filename: /config/providers.yml
experimental:
  # localPlugins:
  #   honeypot-middleware:
  #     moduleName: github.com/CorySanin/honeypot-middleware
  plugins:
    honeypot-middleware:
      moduleName: github.com/CorySanin/honeypot-middleware
      version: v0.0.1